baseURL = "https://pollen-robotics.github.io/reachy-docs/"
languageCode = "en-us"
title = "Reachy manual"
theme = "book"
googleAnalytics = "UA-92714924-1"
enableEmoji = true

[params]
  BookRepo = "https://github.com/pollen-robotics/reachy-docs"
  BookEditPath = "edit/master/content"
